sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 10
before_install:
  - npm i -g npm@6.13.7
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run semantic-release